export const KUDUS_FETCH_ALL_PENDING = 'KUDUS_FETCH_ALL_PENDING';
export const KUDUS_FETCH_ALL_SUCCESS = 'KUDUS_FETCH_ALL_SUCCESS';
export const KUDUS_FETCH_ALL_FAILURE = 'KUDUS_FETCH_ALL_FAILURE';

export const KUDUS_DASHBOARD_CONTROLS_CHANGE = 'KUDUS_DASHBOARD_CONTROLS_CHANGE';